# ===============================
# Configuración de MongoDB (Clean Code)
# ===============================
# Usa la variable MONGODB_URI. Si no existe en tu PC, usa localhost por defecto.
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}

# Usa la variable MONGO_DB. Si no existe, usa tu base de datos 'Pos'.
spring.data.mongodb.database=${MONGO_DB:pos}

# ===============================
# Configuración del Servidor
# ===============================
# Puerto donde correrá tu API (puedes cambiarlo con la variable PORT)
server.port=${PORT:8080}